app/views/records/_form.html.erb

It is not an inline-form.
Formerly looked like this:
pm](https://cloud.githubusercontent.com/assets/92044/5714881/a8b7f15c-9a94-11e4-8793-eab2f944c23d.png)
Now it looks like this:
pm](https://cloud.githubusercontent.com/assets/92044/5714882/afbbc564-9a94-11e4-8f9e-49137aec82fc.png)

Remove form-inline class from form. Fixes #58

---

app/inputs/multi_value_input.rb

MultiValueInput#input is responsible for how to draw it.

MultiValueInput#collection is responsible for what to draw.

---

app/assets/javascripts/hydra-editor/manage_repeating_fields.js

Extracted createNewField() and _changeControlsToRemove() from
_newField()

Refactor javascript to allow overriding of createNewField()

---

app/inputs/multi_value_input.rb
spec/inputs/multi_value_input_spec.rb

In a subclass the field may not be text (e.g. select box)

Rename build_text_field to build_field

---

app/forms/hydra_editor/form.rb
spec/forms/hydra_editor_form_spec.rb

This should fix the errors in sufia:
```
ActionView::Template::Error:
undefined method `include?' for nil:NilClass
```

Initialize required fields so an NPE is avoided in required?()

---

app/inputs/multi_value_input.rb

Allows subclasses a bit more flexibility to build HTML fields and/or set options

Split option-building from field-building

---

.travis.yml
Gemfile
hydra-editor.gemspec
spec/test_app_templates/Gemfile.extra
spec/test_app_templates/lib/generators/test_app_generator.rb

Versions < 1.0 should not test Fedora4. Also need to clean up the testing process to support Rails 4.2.

Don't test Fedora 4, and clean up testing on Travis

---

Gemfile

This relates to sass/sass#1656. bootstrap-sass 3.3.5 introduced a
regression which causes the Blacklight default CSS to fail its build.

Pin bootstrap-sass to 3.3.4.1 for rails 4.1 build

---

app/views/records/_form_header.html.erb
config/locales/hydra_editor.yml

Adds very basic explanation of the tab/enter keys for keyboard-only users (or users who simply prefer the keyboard)

Add form instructions for screen readers

---

app/assets/stylesheets/hydra-editor/multi_value_fields.scss

Make add and remove button the same size

---

app/forms/hydra_editor/form.rb
app/presenters/hydra/presenter.rb
app/views/records/edit_fields/_default.html.erb
spec/presenters/hydra_editor_presenter_spec.rb
spec/views/records/edit_fields/_default.html.erb_spec.rb

to the presenter.  Deprecate the class versions of `multiple?` and `unique?`
on the presenter, but moved a non-deprecated class verison of `multiple?`
to the `Form`.  Presenters generally shouldn't need to deal with setting
`model_class`, so when these deprecated methods are removed we can get rid
of that.

Add an instance method version of multiple?

---

.gitignore
.travis.yml
Rakefile
hydra-editor.gemspec
solr/config/_rest_managed.json
solr/config/admin-extra.html
solr/config/elevate.xml
solr/config/mapping-ISOLatin1Accent.txt
solr/config/protwords.txt
solr/config/schema.xml
solr/config/scripts.conf
solr/config/solrconfig.xml
solr/config/spellings.txt
solr/config/stopwords.txt
solr/config/stopwords_en.txt
solr/config/synonyms.txt
solr/config/xslt/example.xsl
solr/config/xslt/example_atom.xsl
solr/config/xslt/example_rss.xsl
solr/config/xslt/luke.xsl
spec/features/create_record_spec.rb

Ported over from the similar update to hydra-derivatives.
Fixes the build.

Solr/Fedora Wrapper

---

spec/spec_helper.rb

Code pilfered from spotlight and the dozen other apps that have to do
the same workaround.

Silence Devise deprecation in test configuration

---

app/assets/javascripts/hydra-editor/field_manager.es6

Fixes https://github.com/projecthydra/sufia/issues/2705
Uses the class selector instead of actual html tag. This allows for any kind of tag to be used, such as `input` or `textarea`.

Use class selector for specifying a field's children

---

Rakefile
app/assets/javascripts/hydra-editor/field_manager.es6
spec/javascripts/manage_fields_spec.js

Extracts behavior of creating new child fields to a separate method for easier testing. Provides test coverage for previous commit as requested by @jcoyne.

Test for adding input or textarea child fields

---

app/assets/javascripts/hydra-editor/field_manager.es6
spec/javascripts/manage_fields_spec.js

If you've created more complex fields for, e.g., nested objects the "Add additional" link includes every label all mushed together. This is the fix.
@projecthydra/hyrax-code-reviewers

Use first label to avoid smushing nested labels in more complex fields

---

app/forms/hydra_editor/form.rb
app/presenters/hydra/presenter.rb
spec/forms/hydra_editor_form_spec.rb

This allows us to decouple the cardinality of the form fields from
the cardinality defined in the model.

Allow setting a custom field_metadata_service

---

app/helpers/concerns/records_helper_behavior.rb
spec/helpers/records_helper_spec.rb

This enables Hyrax to use presenters to use a path like
`app/views/collections/edit_partials` rather than
`app/views/hyrax/form/collection_edit_forms/edit_partials`

Use ActiveModel::Naming to find partials

---

hydra-editor.gemspec

Beginning with `v3.5.1`, Simple Form now requires models passed to it to conform
to the `ActiveModel` interface; particularly, they must implement
`#to_model`. We will restrict to `<= 3.5.0` to prevent unexpected breakage for
downstream apps.
Support for `v3.5.1` and up should be readded (this may just require
testing/documentation fixes) and a major version released to get us back to
tracking current `simple_form` development.
See also: https://github.com/samvera/hyrax/pull/2758 and
https://github.com/plataformatec/simple_form/issues/1549.

Restrict `simple_form` to `<= 3.5.0`

---

app/forms/hydra_editor/form.rb
spec/forms/hydra_editor_form_spec.rb

For non-multiple terms, an empty string value is replaced by nil.
Fixes #146.

Updates HydraEditor::Form.model_attributes.

---

.circleci/config.yml
.rubocop.yml

Addresses this with the following:
- Removing the "working directory" CircleCI configuration step
- Ensuring that "bundle install" is run before and after the internal test app. is
generated
- Fixing the Rubocop configuration

Ensures that RSpec and Rubocop run without error

---

.circleci/config.yml
History.md
hydra-editor.gemspec
lib/hydra_editor/version.rb

This is issued in response to GHSA-r74q-gxcg-73hx.  Please see https://github.com/samvera/hydra-editor/pull/180 for an earlier pull request which I issued from my fork.

Updating the simple_form dependency to use 5.0.x releases and releases version 5.0.1

---

hydra-editor.gemspec

As far as I can tell, `thor` is never used explicitly in `hydra-editor` and thus the dependency on it can be removed.
See https://github.com/samvera/browse-everything/issues/338 for related work in `browse-everything`.

Remove unnecessary thor dependency

---

app/assets/stylesheets/hydra-editor/multi_value_fields.scss

With the following CSS
```css
.multi_value .listing li:first-of-type .remove { display: none; }
.multi_value .listing li:first-of-type { width: 83.333333%; }
```
I get the ![following UI](https://user-images.githubusercontent.com/2130/106814035-c8a28900-663f-11eb-8d33-fc9b1d641de7.png)
I spent some time working through the javascript, and it's a rather nasty labyrinth.  First, all multi-values are written by JS (see the [field_manager.es6 file in Hydra::Editor](https://github.com/samvera/hydra-editor/blob/b0d0eee963ebff8d5769b7e535542ab48f252c07/app/assets/javascripts/hydra-editor/field_manager.es6#L1)).  My hope was to be able to discard the "X Remove" button from the HTML of the first element.  However, that proved difficult as there's an assumption that that HTML will be around when we …

Hiding the link that could remove required input

---

app/inputs/multi_value_input.rb

squash out error prone local logic for array casting, use `Kernel#Array`
instead.
the older logic would fail to cast in the case that the value was a String,
requiring a tight integration between the forms input objects and the
application's forms/models. since the very next line is going to fail if we fail
to cast to an Array, let's do so aggressively here.
it looks as though this line once used `Array#wrap` for this, but this only
works if the object responds to `#to_ary` (Ruby's implicit cast); otherwise
it results in a value like `[["blah"]]`. `Kernel#Array` is willing to perform an
explicit cast.

use `Kernel#Array` to cast values to an Array

---

.circleci/config.yml

Fixes #195 
This PR adds the Circle CI step that fails if the branch name is master.

Adds Circle CI step that fails if branch name is master

---

.circleci/config.yml
hydra-editor.gemspec

Resolves #206 and also provides the following:
- Updates the CircleCI Ruby releases to the following:
- 2.7.5
- 2.6.9
- Pins the release of `psych` to the 3.3.z series
- Updates `bundler` to release `2.3.10`

Ensures that CircleCI executes nightly test suites

---

lib/hydra_editor/version.rb

Relaxes restrictions on activerecord and rails dependencies for Rails 6.1 support  (#210)

Prepare for 6.1 release

---

hydra-editor.gemspec
lib/hydra_editor/engine.rb

Somehow everything passed in #216, but broke in `main` possibly due to new releases of other core components.
- Explicitly require hydra-head for zeitwerk
- Restrict to `simple_form` less than 5.2 (released recently)

Fix failing build

---

.github_changelog_generator
CHANGELOG.md
hydra-editor.gemspec
lib/hydra_editor/version.rb

See CHANGELOG changes below for details.

Release prep 6.2

---

app/forms/hydra_editor/form.rb

Forked the hydra-editor and tested removing the "autoload :Permissions". Rails should automatically load the files in the subfolder. This line was causing errors on our hyrax 4 / Rails 6 setup.
My removing the command this error stopped.

Removal of "autoload :Permissions"

---

app/forms/hydra_editor/form.rb
spec/forms/hydra_editor_form_permissions_spec.rb
spec/forms/hydra_editor_form_spec.rb

hydra-editor may not have been modernized when upgrading to rails 5 which made a switch from expecting hashes to ActionController::Parameter objects.  This seems to have slipped by because ActionController::Parameter == Hash as being tested in the spec test was still supported by Rails although deprecated.  In Rails 7.2 this comparison has been dropped which caused the tests to fail and my quick solution at the time was to match the inline comment above the #model_attributes method and return a hash.  This broke tests in Hyrax when upgrading to Rails 7.2.  It seems like changing the tests to expect ActionController::Parameter objects instead of hashes is probably the better solution.
See https://github.com/rails/rails/commit/43e42c1ea879de70d42caa0acbc9b24faf74dc1a

Modernize hydra-editor to assume ActionController::Parameter

---

.github_changelog_generator
CHANGELOG.md
hydra-editor.gemspec
lib/hydra_editor/version.rb

The changes in #225 change the return value of `model_attributes` which has downstream implications so I think this should be a major version.  We probably should add some more notes about upgrading in the README or github release notes.

Release v7
