samvera/hydra-editor

- config/jetty.yml
Makes things easier when running other jetty apps
> Allow overriding jetty port

- app/forms/hydra_editor/form.rb
- app/presenters/hydra/presenter.rb
- app/services/hydra_editor/field_metadata_service.rb
- spec/presenters/hydra_editor_presenter_spec.rb
> multiple? shouldn't raise errors when confronted with non-properties

- LICENSE.txt
- README.md
> Project was moved out of labs, so CI link needs to be updated too.

- app/assets/javascripts/hydra-editor/manage_repeating_fields.js
- app/assets/stylesheets/hydra-editor/multi_value_fields.scss
- spec/javascripts/manage_fields_spec.js
This PR is a result from a conversation started over in Sufia: https://github.com/projecthydra/sufia/issues/2021#issuecomment-219096513.
> Improved multi-field accessibility and usability.

- .travis.yml
- Gemfile
- app/helpers/concerns/records_helper_behavior.rb
- hydra-editor.gemspec
- spec/features/create_record_spec.rb
- spec/forms/hydra_editor_form_spec.rb
- spec/presenters/hydra_editor_presenter_spec.rb
- spec/spec_helper.rb
- spec/support/controller_level_helpers.rb
- spec/views/records/_form.html.erb_spec.rb
Also updated the engine_cart stanza
> Support for Rails 5

- app/assets/javascripts/hydra-editor/field_manager.es6
Ref https://github.com/projecthydra-labs/hyrax/issues/1018
> Make DOM manipulations idempotent.

- hydra-editor.gemspec
- spec/controllers/records_controller_spec.rb
- spec/factories/users.rb
- spec/features/create_record_spec.rb
- spec/features/record_editing_spec.rb
- spec/spec_helper.rb
See: https://robots.thoughtbot.com/factory_bot
> Change FactoryGirl dependency to FactoryBot

- CONTRIBUTING.md
- History.md
- README.md
Also extends the release history in preparation for 4.0.0.rc1
> Updating the README for Samvera Community branding and an update guide

- History.md
- lib/hydra_editor/version.rb
After testing this on Hyrax (2.0.1 and 2.1.0 beta) and an implementation of Valkyrie, no breaking changes appear to have been introduced
> Releasing 4.0.0

- History.md
- lib/hydra_editor/version.rb
This has been tested this on Hyrax (2.0.1 and 2.1.0 beta) along with an implementation of Valkyrie.  No breaking changes appear to have been introduced.
> Releases 3.4.0

- History.md
- hydra-editor.gemspec
- lib/hydra_editor/version.rb
Updating the authors, email, and homepage information for the Gem
> Updates the Gemspec for releases

- app/inputs/multi_value_input.rb
- spec/inputs/multi_value_input_spec.rb
> MultiValue gets values from object methods and attributes

- README.md
- hydra-editor.gemspec
- spec/spec_helper.rb
Resolves #155 by addressing the following:
- Adding the simplecov and coveralls Gem dependencies
- Integrating Coveralls reporting
- Updating the README with a Coveralls badge
> Integrates Coveralls reporting

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SUPPORT.md
Resolve #156; Link to contribution guidelines
> Update docs to match templates

- .travis.yml
- Gemfile
- hydra-editor.gemspec
- spec/factories/users.rb
- spec/features/create_record_spec.rb
- spec/inputs/multi_value_input_spec.rb
- spec/views/records/_form.html.erb_spec.rb
> Updating the Travis CI build matrix to use Ruby releases 2.5.1 and 2.4.4 along with Rails releases 5.2.1, 5.1.6, and 5.0.7

- .rubocop.yml
- .rubocop_todo.yml
- Gemfile
- app/presenters/hydra/presenter.rb
- hydra-editor.gemspec
- lib/hydra_editor/engine.rb
- spec/controllers/records_controller_spec.rb
- spec/features/create_record_spec.rb
- spec/features/record_editing_spec.rb
- spec/forms/hydra_editor_form_permissions_spec.rb
- spec/forms/hydra_editor_form_spec.rb
- spec/helpers/records_helper_spec.rb
- spec/inputs/multi_value_input_spec.rb
- spec/javascripts/jasmine_spec.rb
- spec/javascripts/support/jasmine_helper.rb
- spec/views/records/_form.html.erb_spec.rb
- spec/views/records/edit_fields/_default.html.erb_spec.rb
> Introduces the bixby Gem as a dependency

- .circleci/config.yml
- .gitignore
- .rubocop.yml
This gem had a particularly verbose config. This attempts to trim it
down and normalize with other gems that use engine_cart.
Re: samvera/maintenance#20
Re: samvera/maintenance#21
> Update CircleCI Ruby and Rails versions

- .github_changelog_generator
- CHANGELOG.md
- Gemfile
- README.md
- lib/hydra_editor/version.rb
Added github_changelog_generator, updated changelog, version, and 
README.
> Prepare for 5.0.2 release

- .github_changelog_generator
- CHANGELOG.md
- README.md
- lib/hydra_editor/version.rb
Updated version, CHANGELOG, and a small typo fix in the README.
> Prepare for 5.0.3 release

- .github_changelog_generator
- CHANGELOG.md
- README.md
- lib/hydra_editor/version.rb
Also fix branch names in the README.
> Prepare 6.0.0 release

- .circleci/config.yml
- README.md
- spec/features/create_record_spec.rb
- spec/features/record_editing_spec.rb
- spec/javascripts/jasmine_spec.rb
This is necessary in order to request from the community renewed efforts for maintenance, and to direct those outside of the community to the Samvera Slack.
> Updating the Product Owner information in preparation for the 2022 autumn request for maintenance

- .circleci/config.yml
- app/forms/hydra_editor/form.rb
- hydra-editor.gemspec
Remove unsupported ruby/rails versions from testing
Relax rails dependencies
> Test with latest ruby/rails versions
